[main]
  host = ":8808"
  timeout = 60
  ginmode = ""
  testtable = ""
  maxdbidleconns = 10
  maxdbopenconns = 10

[mysql]
  [mysql.1]
  host = "10.73.29.81:3306"
  user = "faraday"
  pswd = "123456"
  db = "faraday"

